1. Count the number of non-zero values in the array

In [1]:
import numpy as np

# Example array
array = np.array([0, 1, 2, 0, 3, 4, 0])

# Count the number of non-zero values
non_zero_count = np.count_nonzero(array)
print("Number of non-zero values:", non_zero_count)


Number of non-zero values: 4


2. How to create an empty and a full NumPy array?

In [2]:
import numpy as np

# Create an empty array (uninitialized)
empty_array = np.empty((3, 3))
print("Empty array:\n", empty_array)

# Create a full array with all elements as a specific value (e.g., 7)
full_array = np.full((3, 3), 7)
print("Full array:\n", full_array)


Empty array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


3. Find the number of rows and columns of a given matrix using NumPy

In [3]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the number of rows and columns
rows, cols = matrix.shape
print("Number of rows:", rows)
print("Number of columns:", cols)


Number of rows: 3
Number of columns: 3


4. Find the sum of values in a matrix

In [4]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the sum of all values in the matrix
matrix_sum = np.sum(matrix)
print("Sum of values in the matrix:", matrix_sum)


Sum of values in the matrix: 45


5. Calculate the sum of the diagonal elements of a NumPy array 33 and 44

In [5]:
import numpy as np

# Example 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Sum of diagonal elements
diagonal_sum_3x3 = np.trace(matrix_3x3)
print("Sum of diagonal elements in 3x3 matrix:", diagonal_sum_3x3)

# Example 4x4 matrix
matrix_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# Sum of diagonal elements
diagonal_sum_4x4 = np.trace(matrix_4x4)
print("Sum of diagonal elements in 4x4 matrix:", diagonal_sum_4x4)


Sum of diagonal elements in 3x3 matrix: 15
Sum of diagonal elements in 4x4 matrix: 34


6. How to inverse a matrix using NumPy

In [6]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
matrix_inverse = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", matrix_inverse)


Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


7. Matrix Multiplication in NumPy

In [7]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)
print("Result of matrix multiplication:\n", result)


Result of matrix multiplication:
 [[19 22]
 [43 50]]


8. Get the maximum and minimum value from given matrix

In [8]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the maximum and minimum values
max_value = np.max(matrix)
min_value = np.min(matrix)
print("Maximum value in the matrix:", max_value)
print("Minimum value in the matrix:", min_value)


Maximum value in the matrix: 9
Minimum value in the matrix: 1


9. Adding and Subtracting Matrices in Python

In [9]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Adding matrices
add_result = np.add(matrix1, matrix2)
print("Addition of matrices:\n", add_result)

# Subtracting matrices
sub_result = np.subtract(matrix1, matrix2)
print("Subtraction of matrices:\n", sub_result)


Addition of matrices:
 [[ 6  8]
 [10 12]]
Subtraction of matrices:
 [[-4 -4]
 [-4 -4]]


10. How to count the frequency of unique values in NumPy array?

In [10]:
import numpy as np

# Example array
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Count the frequency of unique values
unique, counts = np.unique(array, return_counts=True)
frequency = dict(zip(unique, counts))
print("Frequency of unique values:", frequency)


Frequency of unique values: {1: 1, 2: 2, 3: 3, 4: 4}
