# COPY

In [1]:
# Make a copy, change the original array, and display both arrays

import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# VIEW

In [3]:
# Make a view, change the original array, and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=32
print(arr)
print(x)

[32  2  3  4  5]
[32  2  3  4  5]


In [4]:
# Make a view, change the view, and display both arrays
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=32
print(arr)
print(x)

[32  2  3  4  5]
[32  2  3  4  5]


In [6]:
# Print the value of the base attribute to check if an array owns it's data or not
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
