# NumPy Data Types

In [2]:
import numpy as np

In [4]:
# Get the data type of an array object

arr=np.array([1,4,5,6])
print(arr.dtype)

int32


In [5]:
# Get the data type of an array containing strings

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [6]:
# Create an array with data type string

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [7]:
# Create an array with data type 4 bytes integer

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [10]:
# Change data type from float to integer by using 'i' as parameter value

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [12]:
# Change data type from float to integer by using int as parameter value

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [13]:
# Change data type from integer to boolean

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
